<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import AppNavbar from '@/components/AppNavbar.vue'
import AppPage from '@/components/AppPage.vue'
import BaseCard from '@/components/BaseCard.vue'
import QualificationStatusCard from '@/components/QualificationStatusCard.vue'
import StatusTag from '@/components/StatusTag.vue'
import { usePageResource } from '@/composables/usePageResource'
import { merchantCooperationService } from '@/services/merchant-cooperation'
import { openSubPage } from '@/utils/navigation'

const { status, data, errorMessage, load } = usePageResource(merchantCooperationService.getBusinessQualification)
const checkTone = (value: string) => value === 'passed' ? 'success' : value === 'failed' ? 'error' : 'pending'
onLoad(load)
</script>

<template>
  <AppPage :status="status" :state-message="errorMessage" secondary @retry="load">
    <template #navbar><AppNavbar title="经营资格" centered show-back /></template>
    <view v-if="data" class="stack qualification-page"><BaseCard class="merchant-summary"><text class="merchant-summary__project">{{ data.projectName }}</text><text class="merchant-summary__name">邻里生鲜（大光路店）</text><text class="merchant-summary__time">最近核对 {{ data.checkedAt }}</text></BaseCard><QualificationStatusCard title="第一部分｜业务经营资格" :status="data.business.status === 'valid' ? '有效' : '无效'" :tone="data.business.status === 'valid' ? 'success' : 'error'" :description="data.business.description"><view class="scope-list"><view v-for="scope in data.business.scopes" :key="scope.businessType" class="scope-item"><view><text>{{ scope.businessType }}</text><StatusTag :tone="scope.canMaintain ? 'success' : 'error'">{{ scope.canMaintain ? '可维护' : '不可维护' }}</StatusTag></view><text>授权类目：{{ scope.categories.join('、') }}</text></view></view><view class="check-list"><view v-for="check in data.business.checks" :key="check.label" class="check-item"><text class="check-item__icon">{{ check.status === 'passed' ? '✓' : check.status === 'failed' ? '×' : '•' }}</text><view><text>{{ check.label }}</text><text>{{ check.description }}</text></view><view v-if="check.actionText" class="check-action" @click="openSubPage(check.actionPath)">{{ check.actionText }} ›</view></view></view></QualificationStatusCard><QualificationStatusCard title="第二部分｜资金接入状态" :status="({ unconfigured: '未配置', configuring: '配置中', ready: '可交易', exception: '异常' } as const)[data.fund.status]" :tone="data.fund.status === 'ready' ? 'success' : data.fund.status === 'exception' ? 'error' : 'pending'" :description="data.fund.description"><view class="fund-update">状态更新于 {{ data.fund.updatedAt }}；本页面只读，不展示或维护资金敏感配置。</view></QualificationStatusCard><QualificationStatusCard title="第三部分｜正式交易资格" :status="data.formalTrade.status === 'available' ? '具备' : '暂未具备'" :tone="data.formalTrade.status === 'available' ? 'success' : 'pending'" :description="data.formalTrade.description"><view class="check-list"><view v-for="check in data.formalTrade.checks" :key="check.label" class="check-item"><text class="check-item__icon" :class="`check-item__icon--${checkTone(check.status)}`">{{ check.status === 'passed' ? '✓' : check.status === 'failed' ? '×' : '•' }}</text><view><text>{{ check.label }}</text><text>{{ check.description }}</text></view></view></view><view v-if="data.formalTrade.status === 'unavailable'" class="trade-conclusion"><text>系统判定结果</text><text>暂未具备正式交易资格</text><text>可继续维护经营内容，资金能力完成后再开展生产正式收款。</text></view></QualificationStatusCard><view class="qualification-help"><text>业务经营资格与正式交易资格分别判断。资金异常不会改变主体审核结果，也不会把业务资格显示为失败。</text></view></view>
  </AppPage>
</template>

<style scoped lang="scss">
.qualification-page{gap:$space-3}.merchant-summary{background:$color-primary-light}.merchant-summary__project,.merchant-summary__name,.merchant-summary__time{display:block}.merchant-summary__project{color:$color-primary;font-size:13px}.merchant-summary__name{margin-top:2px;font-size:19px;font-weight:700}.merchant-summary__time{margin-top:$space-2;color:$color-text-secondary;font-size:12px}.scope-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:$space-2}.scope-item{padding:$space-3;border-radius:$radius-md;background:$color-group-bg}.scope-item>view{display:flex;align-items:center;justify-content:space-between;gap:$space-2;font-weight:700}.scope-item>text{display:block;margin-top:$space-2;color:$color-text-secondary;font-size:12px}.check-list{margin-top:$space-3}.check-item{display:flex;min-height:52px;align-items:center;gap:$space-2;padding:$space-2 0;border-top:1px solid rgba(225,228,230,.72)}.check-item__icon{display:flex;width:24px;height:24px;flex:none;align-items:center;justify-content:center;border-radius:50%;background:$color-success-light;color:$color-success;font-weight:700}.check-item__icon--pending{background:$color-warning-light;color:$color-warning}.check-item__icon--error{background:$color-error-light;color:$color-error}.check-item>view:not(.check-action){flex:1;min-width:0}.check-item>view>text{display:block}.check-item>view>text:first-child{font-weight:600}.check-item>view>text:last-child{color:$color-text-secondary;font-size:12px}.check-action{display:flex;min-height:44px;align-items:center;color:$color-primary;font-size:13px}.fund-update{padding:$space-3;border-radius:$radius-md;background:$color-warning-light;color:$color-warning;font-size:13px}.trade-conclusion{display:flex;align-items:center;flex-direction:column;margin-top:$space-3;padding:$space-4;border:1px solid $color-border;border-radius:$radius-md;background:$color-group-bg;text-align:center}.trade-conclusion text:first-child{color:$color-text-secondary;font-size:12px}.trade-conclusion text:nth-child(2){margin-top:$space-1;color:$color-warning;font-size:17px;font-weight:700}.trade-conclusion text:last-child{margin-top:$space-2;color:$color-text-secondary;font-size:13px}.qualification-help{padding:$space-3;border-radius:$radius-md;background:$color-primary-light;color:$color-primary;font-size:13px}
</style>
