<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import AppButton from '@/components/AppButton.vue'
import AppIcon from '@/components/AppIcon.vue'
import AppNavbar from '@/components/AppNavbar.vue'
import AppPage from '@/components/AppPage.vue'
import BaseCard from '@/components/BaseCard.vue'
import BottomActionBar from '@/components/BottomActionBar.vue'
import StatusTag from '@/components/StatusTag.vue'
import { merchantTradeService } from '@/services/trade'

const code = ref('')
const candidate = ref<any>(null)
const checking = ref(false)
const lookup = async () => { if (!code.value.trim()) { uni.showToast({ title: '请扫码或输入核销码', icon: 'none' }); return }; checking.value = true; try { candidate.value = await merchantTradeService.lookupVerification(code.value) } finally { checking.value = false } }
const scan = () => uni.scanCode({ success: ({ result }) => { code.value = result; lookup() }, fail: () => uni.showToast({ title: '扫码未完成，可手动输入核销码', icon: 'none' }) })
const confirm = () => { if (candidate.value?.kind !== 'ready') return; uni.showModal({ title: '确认核销', content: '请确认居民、商品、数量与履约地点无误。确认后不可撤销。', success: async ({ confirm }) => { if (confirm) { try { await merchantTradeService.confirmVerification(candidate.value.order.id); candidate.value = await merchantTradeService.lookupVerification(code.value); uni.showToast({ title: '核销成功，订单已完成', icon: 'success' }) } catch (error) { uni.showToast({ title: error instanceof Error ? error.message : '核销失败', icon: 'none' }) } } } }) }
onLoad((options) => { code.value = typeof options?.code === 'string' ? options.code : ''; if (code.value) lookup() })
</script>

<template>
  <AppPage secondary :with-bottom-action="candidate?.kind === 'ready'">
    <template #navbar><AppNavbar title="订单核销" centered show-back /></template>
    <view class="stack verification-page"><BaseCard class="store-card"><AppIcon name="store" :size="22" /><view><text>当前核销门店 / 操作点</text><text>邻里生鲜（大光路店）</text></view><StatusTag tone="success">核销权限有效</StatusTag></BaseCard><BaseCard><view class="section-title"><AppIcon name="qr" :size="21" /><text>现场核销操作</text></view><text class="scan-description">请扫描居民出示的自提/到店核销码，或手动输入凭证后查询订单。扫码后不会自动核销。</text><AppButton @click="scan"><AppIcon name="qr" :size="19" />立即扫码核销</AppButton><view class="manual"><input v-model="code" maxlength="24" placeholder="输入核销码或订单号" /><AppButton variant="secondary" size="compact" :loading="checking" @click="lookup">查询订单</AppButton></view></BaseCard><BaseCard v-if="candidate" class="candidate-card" :class="{ 'candidate-card--ready': candidate.kind === 'ready', 'candidate-card--error': candidate.kind === 'error' }"><view class="candidate-head"><text>{{ candidate.kind === 'ready' ? '订单信息核对' : candidate.kind === 'already' ? '核销结果' : '无法核销' }}</text><StatusTag :tone="candidate.kind === 'ready' ? 'pending' : candidate.kind === 'already' ? 'success' : 'error'">{{ candidate.kind === 'ready' ? '待核销' : candidate.kind === 'already' ? '已核销' : '异常' }}</StatusTag></view><text class="candidate-message">{{ candidate.message }}</text><template v-if="candidate.order"><view class="verify-row"><text>订单编号</text><text>{{ candidate.order.no }}</text></view><view class="verify-row"><text>提货居民</text><text>{{ candidate.order.memberName }} {{ candidate.order.memberMobile.slice(0, 3) }}****{{ candidate.order.memberMobile.slice(-4) }}</text></view><view class="verify-row"><text>履约方式</text><text>{{ candidate.order.fulfillmentMethod }}</text></view><view v-for="item in candidate.order.items" :key="item.skuId" class="verify-product"><image :src="item.productImage" mode="aspectFill" /><view><text>{{ item.productName }}</text><text>{{ item.skuName }} · ×{{ item.quantity }}</text><text>实付 ¥{{ (item.unitPrice * item.quantity / 100).toFixed(2) }}</text></view></view></template></BaseCard><BaseCard class="verification-rules"><text>异常核销提示</text><view><text>· 凭证不存在、已核销、已失效、状态不可核销、无权限或非当前门店时，系统将阻止确认。</text><text>· 已核销订单返回原核销结果，不会再次完成订单。</text></view></BaseCard></view>
    <BottomActionBar v-if="candidate?.kind === 'ready'"><AppButton variant="secondary" @click="candidate = null">取消 / 重扫</AppButton><AppButton @click="confirm">确认核销</AppButton></BottomActionBar>
  </AppPage>
</template>

<style scoped lang="scss">
.verification-page { gap:$space-3; }.store-card { display:flex; align-items:center; gap:$space-2; }.store-card > view { display:flex; min-width:0; flex:1; flex-direction:column; gap:2px; }.store-card > view text:first-child { color:$color-text-secondary; font-size:12px; }.store-card > view text:last-child { overflow:hidden; font-size:16px; font-weight:700; text-overflow:ellipsis; white-space:nowrap; }.store-card :deep(.status-tag) { min-height:22px; padding:0 6px; border-radius:999px; font-size:11px; }.section-title { display:flex; align-items:center; gap:$space-2; padding-bottom:$space-3; border-bottom:1px solid rgba(225,228,230,.72); font-size:17px; font-weight:700; }.scan-description { display:block; margin:$space-3 0; color:$color-text-secondary; font-size:13px; line-height:20px; }.manual { display:flex; align-items:center; gap:$space-2; margin-top:$space-3; }.manual input { min-width:0; height:44px; flex:1; padding:0 $space-3; border:1px solid $color-border; border-radius:$radius-md; background:$color-group-bg; font-size:14px; }.manual :deep(.app-button) { flex:none; }.candidate-card { border-color:rgba(250,77,79,.45); }.candidate-card--ready { border-color:rgba(27,77,83,.55); }.candidate-head { display:flex; align-items:center; justify-content:space-between; gap:$space-2; }.candidate-head text { font-size:17px; font-weight:700; }.candidate-head :deep(.status-tag) { min-height:22px; padding:0 6px; border-radius:999px; font-size:12px; }.candidate-message { display:block; margin-top:$space-2; color:$color-text-secondary; font-size:13px; line-height:20px; }.verify-row { display:flex; align-items:center; justify-content:space-between; gap:$space-3; padding-top:$space-3; color:$color-text-secondary; font-size:13px; }.verify-row text:last-child { color:$color-text-primary; text-align:right; }.verify-product { display:flex; align-items:center; gap:$space-3; margin-top:$space-3; padding:$space-3; border-radius:$radius-md; background:$color-group-bg; }.verify-product image { width:56px; height:56px; border-radius:$radius-sm; }.verify-product > view { display:flex; flex:1; flex-direction:column; gap:2px; }.verify-product text:first-child { font-size:15px; font-weight:600; }.verify-product text:not(:first-child) { color:$color-text-secondary; font-size:12px; }.verify-product text:last-child { color:$color-accent; font-size:14px; font-weight:700; }.verification-rules { display:flex; flex-direction:column; gap:$space-2; background:$color-group-bg; }.verification-rules > text { color:$color-error; font-size:15px; font-weight:700; }.verification-rules > view { display:flex; flex-direction:column; gap:$space-1; color:$color-text-secondary; font-size:12px; line-height:18px; }
</style>
